name: Deploy with Docker to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t 651161789299.dkr.ecr.ap-south-1.amazonaws.com/dhagad_image:${IMAGE_TAG} \
            -t 651161789299.dkr.ecr.ap-south-1.amazonaws.com/dhagad_image:latest \
            .

      - name: Push images to ECR
        run: |
          docker push 651161789299.dkr.ecr.ap-south-1.amazonaws.com/dhagad_image:${IMAGE_TAG}
          docker push 651161789299.dkr.ecr.ap-south-1.amazonaws.com/dhagad_image:latest

      - name: Stop old container
        run: |
          docker stop flask-container || true
          docker rm flask-container || true

      - name: Run new container
        run: |
          docker run -d \
            -p 5000:5000 \
            --name flask-container \
            --restart always \
            651161789299.dkr.ecr.ap-south-1.amazonaws.com/dhagad_image:${IMAGE_TAG}